#!/usr/bin/env python3
"""Turn the judged verdicts into seeds.json, keeping human corrections on top.

The pipeline is meant to run unattended, so the place for a human is not in the middle of it. It is
`overrides.json`: a short file that forces a project in or out, and declares the package a repository
publishes. Automation decides everything it can, and the override file records the few cases where a
person disagreed — with a reason, so the next reader knows whether it still applies.

Usage: python3 scripts/seed.py
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OVERRIDES = ROOT / "overrides.json"


def main() -> None:
    verdicts = json.loads((ROOT / "data" / "classified.json").read_text())["verdicts"]
    layers = json.loads((ROOT / "data" / "candidates.json").read_text())["layers"]
    overrides = json.loads(OVERRIDES.read_text()) if OVERRIDES.exists() else {"include": {}, "exclude": {}, "packages": {}}

    placed: dict[str, list[str]] = {key: [] for key in layers}
    for verdict in verdicts.values():
        repo = verdict["repo"]
        if repo in overrides.get("exclude", {}):
            continue
        layer = overrides.get("include", {}).get(repo, {}).get("layer") or verdict.get("layer")
        if (verdict.get("in_stack") or repo in overrides.get("include", {})) and layer in placed:
            placed[layer].append(repo)
    for repo, entry in overrides.get("include", {}).items():
        layer = entry.get("layer")
        if layer in placed and repo not in placed[layer]:
            placed[layer].append(repo)

    packages = overrides.get("packages", {})
    seeds = {
        "_comment": (
            "Generated by scripts/seed.py. Membership is proposed by scripts/discover.py (a measurable "
            "floor) and scripts/classify.py (a model reads each README), then corrected by overrides.json. "
            "Edit overrides.json, not this file."
        ),
        "categories": [
            {
                "id": key,
                "title": layer["title"],
                "blurb": layer["blurb"],
                "repos": [({"repo": repo, "package": packages[repo]} if repo in packages else repo) for repo in sorted(set(placed[key]))],
            }
            for key, layer in layers.items()
            if placed[key]
        ],
    }
    (ROOT / "seeds.json").write_text(json.dumps(seeds, ensure_ascii=False, indent=2) + "\n")
    total = sum(len(category["repos"]) for category in seeds["categories"])
    print(f"{total} projects across {len(seeds['categories'])} layers "
          f"({len(overrides.get('include', {}))} forced in, {len(overrides.get('exclude', {}))} forced out)")


if __name__ == "__main__":
    main()
